In [2]:
# !pip install thefuzz
import itertools
import pandas as pd
#new library
from thefuzz import fuzz,process

In [3]:
df1 = pd.read_csv('companies_1.csv')
df2 = pd.read_csv('companies_2.csv')

Data Processing

create the df dataframe containing the product of the two CSVs

In [4]:
df1.head()

         Date      Open      High       Low     Close   Adj Close    Volume
0  1997-05-15  0.121875  0.125000  0.096354  0.097917  1443120000  0.097917
1  1997-05-16  0.098438  0.098958  0.085417  0.086458   294000000  0.086458
2  1997-05-19  0.088021  0.088542  0.081250  0.085417   122136000  0.085417
3  1997-05-20  0.086458  0.087500  0.081771  0.081771   109344000  0.081771
4  1997-05-21  0.081771  0.082292  0.068750  0.071354   377064000  0.071354

In [5]:
df2.head()

,Date,open,high,low,close,adjclose,volume,ingested_at_utc
0,2016-01-04,54.320000,54.799999,53.389999,54.799999,47.770725,53778000,2026-05-24 06:27:10.232519+00:00
1,2016-01-05,54.930000,55.389999,54.540001,55.049999,47.988651,34079700,2026-05-24 06:27:10.232519+00:00
2,2016-01-06,54.320000,54.400002,53.639999,54.049999,47.116936,39518900,2026-05-24 06:27:10.232519+00:00
3,2016-01-07,52.700001,53.490002,52.070000,52.169998,45.478073,56564900,2026-05-24 06:27:10.232519+00:00
4,2016-01-08,52.369999,53.279999,52.150002,52.330002,45.617554,48754000,2026-05-24 06:27:10.232519+00:00

In [6]:
cs1 = ['A','B','C']
cs2 = ['A Inc','B & Bros', 'C']

list(itertools.product(cs1,cs2))

[('A', 'A Inc'),
 ('A', 'B & Bros'),
 ('A', 'C'),
 ('B', 'A Inc'),
 ('B', 'B & Bros'),
 ('B', 'C'),
 ('C', 'A Inc'),
 ('C', 'B & Bros'),
 ('C', 'C')]

In [7]:
for cs1,cs2 in list(itertools.product(cs1,cs2)):
    sim = fuzz.ratio(cs1,cs2)

In [11]:
df = pd.DataFrame(
    itertools.product(df1['Close'].values,df2['adjclose']),
    columns=['CSV1','CSV 2']
)

In [12]:
df.head()

       CSV1      CSV 2
0  0.097917  47.770725
1  0.097917  47.988651
2  0.097917  47.116936
3  0.097917  45.478073
4  0.097917  45.617554

In [13]:
df.shape

(19070212, 2)

calculating the levenshtein distance

In [14]:
fuzz.partial_ratio("Apple","Apple Inc.")

100

In [16]:
fuzz.partial_ratio('Microsoft','Apple Inc')

20

In [18]:
fuzz.partial_ratio('Microsoft','MSFT')

40

In [19]:
A = ['Apple','Alphabet','Microsoft']
B = ['MSFT','Alphabet/Google','Apple inc.']

In [20]:
companies = list(itertools.product(A,B))
companies

[('Apple', 'MSFT'),
 ('Apple', 'Alphabet/Google'),
 ('Apple', 'Apple inc.'),
 ('Alphabet', 'MSFT'),
 ('Alphabet', 'Alphabet/Google'),
 ('Alphabet', 'Apple inc.'),
 ('Microsoft', 'MSFT'),
 ('Microsoft', 'Alphabet/Google'),
 ('Microsoft', 'Apple inc.')]

In [21]:
for c1,c2 in companies:
    ratio = fuzz.partial_ratio(c1,c2)
    print(f"{c1} > {c2}: {ratio}")

Apple > MSFT: 0
Apple > Alphabet/Google: 57
Apple > Apple inc.: 100
Alphabet > MSFT: 0
Alphabet > Alphabet/Google: 100
Alphabet > Apple inc.: 46
Microsoft > MSFT: 40
Microsoft > Alphabet/Google: 29
Microsoft > Apple inc.: 31

Create a new column Ratio Score that contains the distance for all the rows in df

In [26]:
score = [fuzz.partial_ratio(str(c1),str(c2)) for c1,c2 in df.values]

In [27]:
score[:10]

[33, 39, 52, 41, 45, 41, 46, 56, 59, 32]

In [28]:
df['Ratio Score'] = score

In [30]:
df.head(10)

       CSV1      CSV 2  Ratio Score
0  0.097917  47.770725           33
1  0.097917  47.988651           39
2  0.097917  47.116936           52
3  0.097917  45.478073           41
4  0.097917  45.617554           45
5  0.097917  45.591393           41
6  0.097917  46.009842           46
7  0.097917  45.016079           56
8  0.097917  46.297497           59
9  0.097917  44.449432           32