In [1]:
import pandas as pd

In [2]:
df1 = pd.read_csv('Fifa.csv')

In [10]:
df2 = pd.read_csv('cleaned_2017-18.csv')

In [7]:
df1.head()

,Name,Country,Position,Age,Overall_Rating,Future Potential,Team,Value Per M$,Total_Stats Score
0,Agostinho Mabululu,Angola,LW,30,68,68,Ittihad Alexandria,0.65,1660
1,Mahmoud Gennesh,Egypt,GK,35,67,67,Ittihad Alexandria,0.35,1620
2,Sobhi Suleiman,Egypt,GK,28,63,65,Ittihad Alexandria,0.20,1480
3,Mahmoud Alaa,Egypt,CB,32,68,68,Ittihad Alexandria,0.50,1695
4,Mahmoud Shabana,Egypt,CB,30,66,66,Ittihad Alexandria,0.40,1640

In [11]:
df2.head()

,rk,player,nation,pos,squad,comp,age,born,Matches Played,Avg Mins per Match,...,Total Shots,% Shots on target,Shots p 90,Goals per shot,Goals per shot on target,% Aerial Duels won,Shot creating actions p 90,Goal creating actions p 90,Crosses Stopped,season
0,1,Patrick van Aanholt,Netherlands,DF,Crystal Palace,Premier League,26,1990,28,2184,...,33,33.3,0.45,0.15,0.45,54.5,1.90,0.16,0,2017-2018
1,2,Rolando Aarons,England,MF,Newcastle Utd,Premier League,21,1995,4,139,...,2,0.0,0.00,0.00,0.00,25.0,0.65,0.00,0,2017-2018
2,3,Rolando Aarons,England,MF,Hellas Verona,Serie A,21,1995,11,517,...,3,0.0,0.00,0.00,0.00,37.5,0.87,0.00,0,2017-2018
3,4,Ignazio Abate,Italy,DF,Milan,Serie A,30,1986,17,1057,...,4,50.0,0.17,0.25,0.50,55.6,2.30,0.34,0,2017-2018
4,5,Aymen Abdennour,Tunisia,DF,Marseille,Ligue 1,27,1989,8,499,...,2,50.0,0.18,0.00,0.00,50.0,0.36,0.00,0,2017-2018

Data Wrangling

1.Merge df1 and df2 with a left join